version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: aws-projects/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws-projects/start_container.sh
      timeout: 300
      runas: root
